language: "c"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get install automake
  - sudo apt-get update -qq
script:
  - ./configure
  - automake --add-missing
  - make
